Repository JHpBB/carrot, pull requests merged in 2024-06, with the labels that each got.

#17 채팅
  README.md
  chat
Labels: bug

#18 병원
  README.md
  hospital
Labels: bug

#19 약국 게시판 추가
  README.md
  pharmacy.md
Labels: bug

#23 구매 추가
  README.md
  purchase.md
Labels: enhancement

#22 생활/편의 페이지 추가
  Life&Convenience
  README.md
Labels: bug

#21 판매 추가
  README.md
  sale.md
Labels: enhancement

#20 미용 추가
  README.md
  beauty.md
Labels: enhancement

#16 운동 게시판 추가
  README.md
  exercise.md
Labels: enhancement

#24 분실/실종 페이지 추가
  README.md
  missing.md
Labels: documentation
